# Generated by Django 4.1.1 on 2022-11-06 20:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Articulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=30)),
                ("resumen", models.CharField(max_length=30, null=True)),
                ("texto", models.CharField(max_length=1000)),
                ("fecha", models.DateField(null=True)),
            ],
            options={
                "verbose_name_plural": "Articulos",
            },
        ),
        migrations.CreateModel(
            name="Seccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_seccion", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name_plural": "Secciones",
            },
        ),
        migrations.AlterModelOptions(
            name="autor",
            options={"verbose_name_plural": "Autores"},
        ),
        migrations.AlterModelOptions(
            name="pagina",
            options={"verbose_name_plural": "Paginas"},
        ),
        migrations.RemoveField(
            model_name="pagina",
            name="nombre",
        ),
        migrations.AddField(
            model_name="pagina",
            name="fecha",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="pagina",
            name="resumen",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="pagina",
            name="texto",
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pagina",
            name="titulo",
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Imagenes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="imagenes"),
                ),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.articulo"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Imagenes",
            },
        ),
    ]
