# Generated by Django 4.1.1 on 2022-11-07 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_articulo_seccion_alter_autor_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagenes",
            name="articulo",
        ),
        migrations.AddField(
            model_name="imagenes",
            name="pagina",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="blog.pagina"
            ),
            preserve_default=False,
        ),
    ]
