# Generated by Django 4.1.1 on 2022-11-07 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_remove_imagenes_articulo_imagenes_pagina"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagenes",
            options={},
        ),
    ]
