# Generated by Django 4.1.1 on 2022-11-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mensajes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emisor", models.IntegerField()),
                ("mensaje", models.CharField(max_length=200)),
                ("avatar", models.ImageField(upload_to="")),
                ("alineamiento", models.CharField(max_length=1)),
            ],
        ),
    ]
